### ISSUE TITLE
Hi! python exception when run script. 

### ISSUE THREAD

**Issue by mailo84** [hyperClink/localdbbookconverter#1]
Hi! python exception when run script. 
can you help? plz

Traceback (most recent call last):
  File "localdbbookconverter/tobookconv.py", line 17, in <module>
    g.write((base64.b64decode(decoding)))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/base64.py", line 88, in b64decode
    return binascii.a2b_base64(s, strict_mode=validate)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
binascii.Error: Invalid base64-encoded string: number of data characters (4873) cannot be 1 more than a multiple of 4

**Comment by hyperClink** [comment]
try the updated code, i forgot to add padding and it worked without it on my machine

**Comment by mailo84** [comment]
same error 
i'm trying to get this book ID 400091

**Comment by hyperClink** [comment]
i was just able to properly decode the book provided, unsure what the issue might be, try the updated files again to see if that helps

**Comment by mailo84** [comment]
Thx! it works!
